#!/bin/bash

function getCoordinates {
	local coordinates=$(curl -s http://whatismycountry.com/ | sed -n 's/.*Coordinates \(.*\)<.*/\1/p')
	echo "${coordinates}"
}

function getHemisphere {
	local firstChar=$(echo "${1}" | cut -c 1-1)
	
	if [ $firstChar == "-" ]; then
		echo false
	else
		echo true	
	fi
}

v=false
c=""

usage() { echo "Usage: $0 [-c <string>]" 1>&2; exit 1; }

while getopts ":c:v" o; do
    case "${o}" in
        c)
            c=${OPTARG}
            ;;
		v)
			v=true
			;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${c}" ]; then
	c=$(getCoordinates)
fi

# use regex to match "float float" example: -73.31 42.31
# -?[0-9]*\.?[0-9]+ -?[0-9]*\.?[0-9]+

isNorth=$(getHemisphere "${c}")

if [ $isNorth = true ] ; then
    echo "north"
else
    echo "south"
fi